version: '3'

services:
  mariadb:
    image: mariadb:10.6
    container_name: nextcloud_subpath_mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql:Z
    environment:
      #- MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./mariadb/db.env

  redis:
    image: redis:alpine
    container_name: nextcloud_subpath_redis
    restart: unless-stopped

  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_subpath_nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
    env_file:
      - ./mariadb/db.env
    depends_on:
      - mariadb
      - redis

  nginx:
    image: nginx
    container_name: nextcloud_subpath_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - nextcloud:/var/www/html:z,ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud

  cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_subpath_cron
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb:
  nextcloud: