# https://github.com/nextcloud/docker
services:
  mariadb:
    image: mariadb:10.6
    container_name: nextcloud_docker_path_mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql:Z
    environment:
      #- MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./mariadb/db.env

  redis:
    image: redis:alpine
    container_name: nextcloud_docker_path_redis
    restart: unless-stopped

  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_docker_path_nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - OVERWRITEWEBROOT=/nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
    env_file:
      - ./mariadb/db.env
    depends_on:
      - mariadb
      - redis

  nginx:
    image: nginx
    container_name: nextcloud_docker_path_nginx
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:z,ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud

  entry_nginx:
    image: nginx
    container_name: nextcloud_docker_path_entry_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./entry_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nginx

  cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_docker_path_cron
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb:
  nextcloud: